spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: homieMatching
  datasource:
    url: jdbc:mysql://106.54.9.18:3306/hjj
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hjj
    password: 13584064183czHJJ
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: 47.116.208.231
    database: 0
    password: 13584064183cz
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: hejiajun.icu
        same-site: lax
        secure: false
        max-age: 864000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
oss:
  accessKeyId:
  accessKeySecret:
  folderName:
  endpoint:
  bucketName: